### ISSUE TITLE
[FEAT] 스프링 5주차 과제🦁

### ISSUE THREAD

**Issue by OaYenn** [OaYenn/Likelion10th_SpringStudy#5]
## 📌  Feature Issue
- 나만의 셀렉샵을 AWS RDS의 MySQL을 연결
- 나만의 셀렉샵을 AWS EC2에 배포

## 📝  To-do
- [x] RDS 구매하고 MySQL세팅
- [x] OG 태그 작업
- [x] EC2 구매, 준비, 배포
- [x] 포트포워딩, nohup 적용
- [x] 도메인 붙이고 카카오톡에 공유
