### ISSUE TITLE
[FEAT] 스프링 3주차 세션

### ISSUE THREAD

**Issue by OaYenn** [OaYenn/Likelion10th_SpringStudy#6]
## 📌  Feature Issue

- 페이지를 만들기 위한 HTML,CSS, Javascript를 익힌다.
- 스프링을 이용해 API를 만들고 기능 확인하는 법을 손에 익힌다.
- 타임라인 서비스를 완성한다.

## 📝  To-do

- [ ] 프로젝트 만들고 API 설계하기
- [ ] Repository, Service, Controller 만들기
- [ ] HTML, CSS 기초
- [ ] Javascript 기초
- [ ] jQuery 기초
- [ ] 클라이언트 설계하기
- [ ] 메모 생성, 조회, 변경, 삭제하기 구현
